version: 2

sources:
  - name: stackoverflow
    description: Stackoverflow public dataset
    database: proud-portfolio-365819
    schema: stackoverflow
    loader: GCP
    tables:
      - name: votes
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_extracted_at
        description: >
            table containing a report of stackoverflow vote data
      - name: post_questions
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_extracted_at
        description: >
            table containing a report of posted questions on stackoverflow
      - name: post_answers
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_extracted_at
        description: >
            table containing a report of posted answers on stackoverflow
      - name: tags
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_extracted_at
        description: >
            table containing a report of tags on the stackoverflow platform  
      - name: comments
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_extracted_at
        description: >
            table containing a report of all the comments in the stackoverflow platform
      - name: users
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _sdc_extracted_at
        description: >
            table containing a report of the users on the stackoverflow platform                     
